### ISSUE TITLE
Pandoc Equation Conceals look ugly / unreadable

### ISSUE THREAD

**Issue by jb567** [romainl/Apprentice#12]
[Vim Pandoc](https://github.com/vim-pandoc/vim-pandoc) and its [syntax plugin](https://github.com/vim-pandoc/vim-pandoc-syntax) use a conceal to hide `\alpha` and other LaTeX equations.

They use highlighting, but under the Apprentice colorscheme, the concealed icons are colored white, with white highlighting making it unreadable as below:
![screenshot](https://cloud.githubusercontent.com/assets/2958573/9695828/3a71c4cc-53ba-11e5-8665-c4e303bc7e73.PNG)

Steps to reproduce

1. `:e foobar.md`
2. `i` `$$\alpha$$` `<CR>`
3. should show the syntax highlighting if pandoc and its syntax equivalent are installed

**Comment by romainl** [comment]
Thank you for opening this issue.

Commit 79d1bf3f120241e930d68b6d4ab9b47bcb6a2f30 seems to fix the issue. Can you test it?

**Comment by jb567** [comment]
![sshot](https://cloud.githubusercontent.com/assets/2958573/9698336/8a915896-5405-11e5-9224-22ac17c8eeaf.PNG) Appears fixed now
