### ISSUE TITLE
support for dark terminal

### ISSUE THREAD

**Issue by eldamir** [romainl/Apprentice#15]
I use the default terminal app on ubuntu, but have set background color to completely opague black. This makes your theme look rather bad. Cannot see the linenumber or highlighted lines.

On a white background, it looks brilliant though. Any chance this could work for both?

**Comment by romainl** [comment]
Hi, could you give me the output of these commands?

In your shell:

    $ echo $TERM

In Vim:

    :echo $TERM
    :echo &t_Co

What colorscheme do you use in your terminal emulator?

Could you post screenshots please?

**Comment by eldamir** [comment]
certainly. Although, you have already lead me to the problem. I usually run vim in a tmux session, so I can pop up extra bash terminals where I want. When doing so `echo $TERM` yiels `screen`, and the theme does not work. When running vim outside of tmux, I get `xterm`, and the theme looks as it should.

For your reference, here is all my output.

## Inside tmux

```
$ echo $TERM
screen
```

```
:echo $TERM
screen
echo &t_Co
256
```

The `&t_Co` is set in my .vimrc

**Comment by eldamir** [comment]
according to [this stack exchange question](http://unix.stackexchange.com/questions/118806/tmux-term-and-256-colours-support), I was lead to try running tmux with `-2` option. This seems to solve the issue.

When I initially had trouble with 256 colors, I simlpy added `set t_Co=256` to my .vimrc, which seemed to fix my troubles, until I tried your theme. Odd.

With `tmux -2`, all is well. Thanks for the pointers :smile:

**Comment by romainl** [comment]
For reference, adding `set t_Co=256` to your `vimrc` is not a very good idea. If you *need* 256 colors support, it is recommended to set your terminal emulator/multiplexer properly instead.

You can find a few pointers [here](https://github.com/romainl/Apprentice/wiki/256-colors-and-you.).

**Comment by eldamir** [comment]
I agree. The reason I did so, was that I didn't understand why colors did not work, eventhough my terminal was configured to use them. Didn't consisder that tmux was messing it up. Thanks for your assistance. And thanks for this theme. It looks really great
