### ISSUE TITLE
AUR package added and request

### ISSUE THREAD

**Issue by bigmittens** [romainl/Apprentice#19]
I made a package in the AUR for Arch users if you want to include that in the installation page of the readme. https://aur.archlinux.org/packages/vim-apprentice/

also: just a request to please keep the format for the filenames of the releases similar since it makes it easier to update the package (currently it's changed between lowercase "apprentice-1.7" to uppercase, using a period "Apprentice.1.8" and uppercase, hyphen "Apprentice-1.9"). thanks :)

**Comment by romainl** [comment]
Well thank you for that. Could you give me a rundown off the install process?

**Comment by bigmittens** [comment]
you can either use an AUR helper (``yaourt -S vim-apprentice``) or you can download the PKGBUILD and ``makepkg -i`` to install.

**Comment by romainl** [comment]
Thank you, I've updated the README.
