### ISSUE TITLE
Better support for background transparency (hi Normal ctermbg=NONE)

### ISSUE THREAD

**Issue by oblitum** [romainl/Apprentice#23]
Despite liking the choice of colours, they better not be exactly the same (comment foreground colour and OverLength background colour are the same):

![screenshot from 2016-07-04 22-04-13](https://cloud.githubusercontent.com/assets/1269815/16571487/89f688d0-4233-11e6-85c1-390fc5c9f11e.png)

I'm using https://github.com/whatyouhide/vim-lengthmatters which highlights long lines using `OverLength`.

### UPDATE

This happens because I use transparent background by setting `hi! Normal ctermbg=NONE` in the .vimrc.

**Comment by romainl** [comment]
Are you using Apprentice in a 8/16 color terminal?

**Comment by oblitum** [comment]
no, it's 256.

**Comment by romainl** [comment]
Check your `$TERM` inside Vim, as well as the value of `t_Co`:

    :echo $TERM
    :echo &t_Co

**Comment by oblitum** [comment]
`$TERM -> screen-256color`
`t_Co -> 256`

**Comment by oblitum** [comment]
Your explanation above should then provide the answer to the behavior I'm having, this is [my setup](https://github.com/oblitum/dotfiles/blob/archlinux/.vimrc#L188-L194):

" Colorscheme {{{
colors apprentice
"colors seoul256-light
hi! link Conceal Normal
hi! Normal ctermbg=NONE
hi! NonText ctermbg=NONE
" }}}

I do that on purpose to get transparent background.

**Comment by romainl** [comment]
You are using Vim in tmux?

It looks fine, here:

<img width="830" alt="capture d ecran 2016-07-05 a 07 37 34" src="https://cloud.githubusercontent.com/assets/344335/16574825/735fab7e-4283-11e6-9360-47e7183bc309.png">

**Comment by oblitum** [comment]
I've just checked that commenting out `NONE` settings made it works as expected. It's indeed nice but, I can't exchange it for losing the background transparency. I'll change the issue title.

**Comment by romainl** [comment]
It appears to be a flaw in vim-lengthmatters's design, not in Apprentice's design.

The author wrongly assumes the value is a color (say `250` or `#bcbcbc` or maybe `fg`) but forgets it could perfectly be `NONE`, in which case he should pick another (default?) color.

I will certainly not change anything in Apprentice to address bugs in other plugins. You should contact the author via [his plugin's issue tracker](https://github.com/whatyouhide/vim-lengthmatters/issues).

**Comment by oblitum** [comment]
Ah, my bad. Sorry to bother then, if the issue is there then that's OK, I thought it was colorscheme's fault. I'll check how to fix this there then, I've done two pull-requests on vim-lengthmatters lately, let's go for the 3rd.

**Comment by oblitum** [comment]
Do you have an advice on what should be picked to play nice with Apprentice?

**Comment by romainl** [comment]
You shouldn't adapt vim-lengthmatters to fit Apprentice (or any other specific colorscheme) or vice-versa.

That plugin obviously needs fallback values but how to define them is a potentially difficult matter.

One elegant but relatively complex way could be to calculate those values from existing ones but that also could lead to weird cornercases… What if we get `NONE` and `NONE`?

A simpler but not very elegant way could be to define arbitrary defaults, possibly based on `&background`.

**Comment by oblitum** [comment]
I'm going to set this on my `.vimrc`, since I'm already deviating from Apprentice default, Lengthmatters also provide options for setting OverLength colours so I'll try to set it ot Apprentice colors before I override them with NONE.
