### ISSUE TITLE
What happend to my colorscheme?

### ISSUE THREAD

**Issue by Leeiio** [romainl/Apprentice#24]
Sorry but i can not post issue in https://github.com/romainl/flattened, so i post here.

The "flattened_light" in my Terminal is like this

<img width="806" alt="2016-09-01 10 17 02" src="https://cloud.githubusercontent.com/assets/218127/18153280/07de3ba2-702f-11e6-8b2d-8b40762a1083.png">

**Comment by romainl** [comment]
Flattened doesn't have an issue tracker because I don't want to provide support for it.
