### ISSUE TITLE
distribute with Vim

### ISSUE THREAD

**Issue by chrisbra** [romainl/Apprentice#31]
As discussed on reddit:
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by romainl** [comment]
No problem. Tell me what needs to be done (change in license, change to the metadata, etc.) and I will do it.

**Comment by chrisbra** [comment]
I don't think any changes are needed. Simply send the file to Bram and mention the ticket 1665. Last Bram said, he would collect them all and decides later what to bundle with Vim.
