### ISSUE TITLE
Airline theme

### ISSUE THREAD

**Issue by jmatraszek** [romainl/Apprentice#36]
Hi, is there any reason for airline/lightline themes to live in a separate branch? As far as I can see it seems pretty outdated compared to `master`.

If you do not wish to keep this in `master`, then maybe merging the airline apprentice theme to https://github.com/vim-airline/vim-airline-themes (do not know if lightline has a similar repo with themes) would be a good idea?

**Comment by romainl** [comment]
Hi, I don't use any *line plugin and I don't plan to support them.

If you feel like submitting the airline theme to vim-airline/vim-airline-themes you can do it as long as you provide any required support.

**Comment by jmatraszek** [comment]
OK, I understand. Thanks!
