### ISSUE TITLE
Background colour not being set correctly in iTerm2

### ISSUE THREAD

**Issue by cdespatie** [romainl/Apprentice#37]
If I had to guess, I'd say this was a configuration problem with my setup rather than a problem with the colorscheme, but posting here anyway since it was requested.

Screenshot: https://i.imgur.com/pjXFggk.png (iTerm2 on left, MacVim on right)
.vimrc: https://gist.github.com/cdespatie/44a1edc483cf08ebba16ff6bd566b5da
iTerm2 version: 3.2.5

**Comment by romainl** [comment]
<img width="697" alt="capture d ecran 2018-11-05 a 21 11 35" src="https://user-images.githubusercontent.com/344335/48023918-72cc9700-e13f-11e8-8e11-f402dd0742dc.png">

That's what I get with this command in a fresh iTerm2 3.2.5 I just downloaded:

    $ vim -Nu NONE +color\ apprentice

Note the black borders corresponding to the terminal window's background, and Vim's dark grey background from Apprentice.
