### ISSUE TITLE
Apprentice breaks loading of color schemes

### ISSUE THREAD

**Issue by fladd** [romainl/Apprentice#42]
It appears that Apprentice breaks the loading of color schemes. Once the color scheme is set to Apprentice, any color scheme that is loaded subsequently is "broken" in the sense that some aspects of the highlighting are lost.
I have observed this behaviour for other more complex color schemes (e.g. Solarized or Gruvbox) as well, but it certainly does not happen for all color schemes.
Is there anything that can be done to prevent this?

**Comment by romainl** [comment]
Bad interactions with other colorschemes have been spotted in the past and I try to mitigate them [here](https://github.com/romainl/Apprentice/blob/master/colors/apprentice.vim#L287).

* Are you using `HEAD` or are you using a previous version?
* Could you come up with a minimal reproductible test case?

**Comment by fladd** [comment]
Yes, sure:

1. Create a file called `test_vimrc` with the following content:
````
set nocompatible
syntax enable
set background=dark
colorscheme pablo
call plug#begin('~/.vim/plugged')
Plug 'romainl/Apprentice'
call plug#end()
````
2. Start vim with `vi -u test_vimrc`
3. Open a new buffer `test.py` and in it type:
```
import os
```
4. Notice the colour of the word `import` (green)
5. Do a `colo apprentice`
6. Do a `colo pablo`
7. Notice the colour of the word `import` (white)

**Comment by fladd** [comment]
And I installed Apprentice with vim-plug today, so I am using `HEAD`.

**Comment by romainl** [comment]
OK, I think I've spotted the issue and I have a solution in mind.

**Comment by fladd** [comment]
Nice!

**Comment by arzg** [comment]
@romainl What were you thinking?

**Comment by romainl** [comment]
@arzg Right now I'm thinking about lunch. But an hour ago I was thinking about keeping a list of existing links in order to restore them.

**Comment by romainl** [comment]
The `ColorSchemePre` event looks interesting: https://github.com/vim/vim/commit/60a68362aa73f4a6cb534688978f9dc2b16e60fe

**Comment by romainl** [comment]
So the problem is that apprentice, too, became overly aggressive and over-engineered in an effort to defend itself against the aggressiveness of popular over-engineered colorschemes. This is an arm race and arm races suck.

**Comment by fladd** [comment]
I am not sure I fully understand. It's just a color schemes we are talking about, right? There is a weird thing going on in Vim-land lately. I have been searching for a new color scheme for days now. Just looking for something simple that sets the highlight groups and looks good. Just doesn't exist...super weird :-)

**Comment by romainl** [comment]
***IDEALLY***, that's what colorschemes should do. That's what Apprentice did before someone convinced me to add those few lines just because some other colorschemes were overly aggressive in their linkings. That's the arms race I was talking about.

For now, I'll remove those lines.

**Comment by romainl** [comment]
@fladd Please try the latest commit.

**Comment by fladd** [comment]
Works, thanks!
