### ISSUE TITLE
Vscode theme port

### ISSUE THREAD

**Issue by gabrielbidula** [romainl/Apprentice#44]
hi guys i did not find anything related to a port for vscode.
does anyone knows how to do it somehow?

cheers

**Comment by romainl** [comment]
Hi, I'm not aware of an existing port for Visual Studio Code or of a Vim-to-{TextMate,Sublime Text,Visual Studio Code} converter that could help in its making.

If you feel adventurous, feel free to create a repo and follow [this official guide](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme).

**Comment by romainl** [comment]
@gabrielbidula you might be interested by [this](https://marketplace.visualstudio.com/items?itemName=amariampolskiy.theme-apprentice&ssr=false#overview).
