### ISSUE TITLE
Iterm2 port

### ISSUE THREAD

**Issue by gabrielbidula** [romainl/Apprentice#46]
Hi, 

I really like this theme but i was not able to reproduce the same colors from vim in iterm2 console (using Xresources export tool from terminal.sexy).

does anyone know how to do it?

thanks!

**Comment by romainl** [comment]
Hi,

You can find an iTerm2 theme [over there](https://github.com/romainl/iterm2-colorschemes/blob/master/apprentice.itermcolors).
