### ISSUE TITLE
New parens matching color is breaking my brain

### ISSUE THREAD

**Issue by gfixler** [romainl/Apprentice#5]
I updated to the latest Apprentice 3 days ago, and for 3 days I've been constantly confused about where my cursor is when dealing with matching parens. I rolled back to see what the difference was. When the matching was white, the opposite paren lit up enough that I would lock onto it. Now that they're a tan brown, the change in the paren is so subtle, that I immediately lock onto the matching paren, highlighted in brown, and my brain tells me that now I'm there. This effect is worse when the parens are near each other - a few characters apart - I feel like I just jumped to the opposite side, and I instantly start hitting motions and commands as though I'm there. For 3 days I've been confused like this and making one error after another. I can always override it, but I thought I'd mention it, as it's an actual issue I'm running into over and over. I didn't even know colors could do this to my head. Would #FFFFAF (also in the palette) be an acceptable alternative?

**Comment by romainl** [comment]
I'm not satisfied with it either. You should probably roll back to an earlier commit or, better, release, while I figure out a better solution.

**Comment by romainl** [comment]
Let me know if [last commit](https://github.com/romainl/Apprentice/commit/5031ecf47ecb59bc6f7d759124f558d035f430a0#diff-a37c82ea85f18af07e0e16945ce9b059) fixes things for you.

**Comment by gfixler** [comment]
That works great. I'm no longer confused, and it fits better than white did, too. Thanks!

**Comment by romainl** [comment]
Good to hear, I will close this ticket, now.
