### ISSUE TITLE
Derivative Works section in README addition

### ISSUE THREAD

**Issue by crajun** [romainl/Apprentice#51]
Discovered a VS Code port of your colourscheme at:

Store link:
https://marketplace.visualstudio.com/items?itemName=amariampolskiy.theme-apprentice

Github:
https://github.com/amariampolskiy/apprentice-vscode

Provides an 'Apprentice Bright' version as well when you install this package, which seems to just bump the colour brightness a little bit.

**Comment by romainl** [comment]
Thank you for the update. Did you jump ships?

**Comment by crajun** [comment]
Nope, just use VS Code occasionally with vim emulation for work and thought I’d check if my colour scheme was available to make me feel more at home.
