### ISSUE TITLE
ModeMsg groups unreadable with cursorline

### ISSUE THREAD

**Issue by slycelote** [romainl/Apprentice#53]
Hi,

Thanks for the wonderful color scheme :)
I found that text highlighted with `ModeMsg` is almost invisible when the cursor line (`:set cursorline`) is over it. For the minimal example, save the following as `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.0)
```

**Comment by romainl** [comment]
`ModeMsg` is a built-in highlight group specifically meant to be used for `:help 'showmode'`. Any other use is at your own risk.

**Comment by slycelote** [comment]
It's used in syntax files shipped with vim: cmake.vim, vim.vim, aml.vim, lace.vim: https://github.com/vim/vim/search?l=Vim+script&q=ModeMsg

**Comment by romainl** [comment]
That's a mistake on the part of their authors but I guess I could give it the `Error` treatment.

**Comment by slycelote** [comment]
Cool, thanks! :)
