### ISSUE TITLE
gVim cursor foreground color

### ISSUE THREAD

**Issue by habamax** [romainl/Apprentice#56]
In gVim text under cursor is barely visible on some syntax highlighted text:

![image](https://user-images.githubusercontent.com/234774/100004005-ed74b780-2dd7-11eb-9dfc-9a55271f71a9.png)

![image](https://user-images.githubusercontent.com/234774/100004033-f6fe1f80-2dd7-11eb-95f1-d9d3bdc4b419.png)

![image](https://user-images.githubusercontent.com/234774/100004108-109f6700-2dd8-11eb-9f4c-1359a9d2da0e.png)

I can fix it in colorscheme event (and I will), but just in case you would like to fix it in your colorscheme:

      hi Cursor guifg=#BCBCBC

**Comment by romainl** [comment]
Thank you, I use the GUI so rarely that it never bothered me but you are definitely right about this usability issue.

I think I will settle with the following, though:

    " fg is #bcbcbc, bg is #262626
    hi Cursor guifg=bg guibg=fg

because whatever colour you chose for bg, there are too many combinations that won't work.

**Comment by habamax** [comment]
yep, that is better, added to my colorscheme override for now.

**Comment by romainl** [comment]
DONE.
