### ISSUE TITLE
Does not load from vimrc (but loads fine manually)

### ISSUE THREAD

**Issue by fladd** [romainl/Apprentice#59]
Having `colorscheme apprentice` in .vimrc will load the default theme (macvim in my case). But when calling `:colorscheme apprentice` manually as a command, it is loaded fine.

```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 19 2020 21:23:05)
macOS version
Included patches: 1-2164
```

**Comment by romainl** [comment]
I use the exact same Vim version (latest MacVim update) without any issue, either via the GUI or via a terminal emulator.

Please try again without anything but `~/.vim/colors/apprentice.vim` and a `vimrc` with `colorscheme apprentice` only.

**Comment by fladd** [comment]
yep, that works, thanks. I apparently had another mistake in my .vimrc. Happy holidays!
