### ISSUE TITLE
Search and DiffAdd having the same colors can be confusing

### ISSUE THREAD

**Issue by sakkemo** [romainl/Apprentice#6]
When doing a search while in diff mode, the stuff that matches gets highlighted with the same color as additional lines (highlight group DiffAdd). I did find this somewhat confusing, first mistaking the added lines as search matches as well.

**Comment by romainl** [comment]
Hi sakkemo, I just pushed a quick fix. Let me know if it is satisfying.

**Comment by romainl** [comment]
Closing this issue.
