### ISSUE TITLE
Problem with bold and italic (vimwiki)

### ISSUE THREAD

**Issue by fedxyz** [romainl/Apprentice#64]
On vimwiki bold and italic formatting doesn't work with Apprentice.
Other themes have problems with italic on terminal but they support at least bold formatting.
With Apprentice this is not possible.

**Comment by romainl** [comment]
Hello, can you add a "broken" screenshot and a "working" screenshot to your issue?

**Comment by fedxyz** [comment]
Here 2 screenshots, first one with Apprentice, second one with another theme.

![Schermata del 2021-09-29 09-34-36](https://user-images.githubusercontent.com/88270312/135224119-989ca52f-e3c5-4525-8004-dcac88536a5b.png)


![Schermata del 2021-09-29 09-37-56](https://user-images.githubusercontent.com/88270312/135224230-162f910c-49c8-4bbc-904c-ff2d108d7b88.png)

**Comment by fedxyz** [comment]
This is the test file I used for the screenshot.
```

# header

**bold**

*italic*

[link](link)
```

**Comment by romainl** [comment]
Could you run the following command:

    :command! SS echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')

and then report what is echoed when you do `:SS` with the cursor on `bold` and `italic`?

FWIW, colorschemes have nothing to do with whether bold or italic work or not in a given environment. Also, Apprentice doesn't handle or override `VimwikiBold` and friends in any way so I'm not sure how it could prevent italic and bold to work.

**Comment by fedxyz** [comment]
On bold I get:
`['mkdNonListItemBlock', 'htmlBold', 'mkdBold']`

on italic I get:
`['mkdNonListItemBlock', 'htmlItalic', 'mkdItalic']`

**Comment by romainl** [comment]
Those highlight groups have nothing to do with Vimwiki.

**Comment by fedxyz** [comment]
I don't know how these were setup. Maybe a conflict with some other plugin?

**Comment by romainl** [comment]
Your markup is wrong.

    **bold**

should be:

     *bold*

and:

    *italic*

should be:

    _italic_

<img width="487" alt="Capture d’écran 2021-09-29 à 09 57 28" src="https://user-images.githubusercontent.com/344335/135227057-24dae4d5-0fd9-48bc-a044-00c096f270c1.png">

**Comment by fedxyz** [comment]
I setup vimwiki to use markdown syntax, this is why I use `**` for bold and `*` for italic.

I tested the file with other themes and some of them seems to support these highlight groups.

For example:
![Schermata del 2021-09-29 10-04-15](https://user-images.githubusercontent.com/88270312/135228350-d0a482f2-feb4-4d6a-a108-9fa4ddac0517.png)

**Comment by romainl** [comment]
Here is what I get with the markdown syntax:

<img width="404" alt="Capture d’écran 2021-09-29 à 10 08 04" src="https://user-images.githubusercontent.com/344335/135228752-1f4a42bb-f8ef-4504-8106-e2ec8b568560.png">

**Comment by fedxyz** [comment]
The output of the commands you asked me to execute:
1 `E411: highlight group not found: mkdNonListItemBlock`
2 `htmlBold       xxx links to Normal  Last set from ~/.vim/bundle/Apprentice/colors/apprentice.vim line 186`


3 `E411: highlight group not found: mkdBold`

4 `E411: highlight group not found: mkdNonListItemBlock`

5 `htmlItalic     xxx links to Normal  Last set from ~/.vim/bundle/Apprentice/colors/apprentice.vim line 187`

6 `E411: highlight group not found: mkdItalic`


I created a test `.vimrc`:
```

set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

Plugin 'romainl/Apprentice'
Plugin 'plasticboy/vim-markdown'
Plugin 'vimwiki/vimwiki'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


set splitbelow
set splitright

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding
set foldmethod=indent
set foldlevel=99

filetype plugin on
syntax on

set termguicolors
colorscheme apprentice

set nu


let g:vimwiki_ext2syntax = {'.wiki': 'markdown'}
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.wiki'}]
autocmd FileType vimwiki set syntax=markdown
```


The output change with/without the markdown plugin but still no bold/italic/underline on link, I attach some screenshots.

I have to say that the red color could have been related to the spellcheck that is disabled now.
If matters I use gnome-terminal.




![Schermata del 2021-09-29 10-32-33](https://user-images.githubusercontent.com/88270312/135233220-252fd2b1-6a0b-4637-b767-4e74126e7d89.png)

![Schermata del 2021-09-29 10-32-57](https://user-images.githubusercontent.com/88270312/135233231-f4fc3a26-1dcd-4fcc-912b-3e002c61d2ce.png)

**Comment by romainl** [comment]
Your problem is caused by this line:

    autocmd FileType vimwiki set syntax=markdown

which overrides Vimwiki's highlight groups.

**Comment by fedxyz** [comment]
You are right. Now it's displayed in the right way, with the correct formatting.

The problem is that this is not a default setting so I added it for some reason/problem and testing I found why: if I remove it I could not use multiline bold/italic text, vimwiki doesn't format it I still see `**` or `*`.

But anyway this is a vimwiki issue I suppose.
Thanks for the help.

**Comment by romainl** [comment]
You are welcom.
