### ISSUE TITLE
Idea: link CurSearch to IncSearch

### ISSUE THREAD

**Issue by craigmac** [romainl/Apprentice#68]
I have trouble with current highlight figuring out which match I'm currently on, especially with a light cursor against a yellow background. I link CurSearch to IncSearch so that I can see exactly which one I'm currently on (with vim-cool). What do you think?

`hi! link CurSearch Search` Hard to see where cursor currently is:
<img width="1904" alt="Screen Shot 2022-05-02 at 10 54 53 AM" src="https://user-images.githubusercontent.com/7416158/166256435-1f494879-b2b1-4489-bf16-42fb6b480f90.png">

`hi! link CurSearch IncSearch` Now I can tell:
<img width="1904" alt="Screen Shot 2022-05-02 at 10 55 13 AM" src="https://user-images.githubusercontent.com/7416158/166256618-e839abde-97b2-429c-853c-d2eb3c45e75b.png">

Would linking CurSearch to IncSearch be a better default? I'm not too familiar with colorscheme stuff in Vim, so I don't know how setting this link would affect other things.

**Comment by romainl** [comment]
Hi. I agree with you, linking `CurSearch` to `IncSearch` makes the most sense and I actually brought it up in https://github.com/vim/vim/pull/10133 but Bram's rebuttal also makes sense, especially given the current state of the feature, which seems unfinished.

I will probably make the link to `IncSearch` when I am sure the feature is ready.

**Comment by craigmac** [comment]
Oh wow, I had no idea `CurSearch` was sort of new!

**Comment by jmdevin** [comment]
Would it be appropriate to revisit adding this idea now?

**Comment by jmdevin** [comment]
@romainl , since this is closed I'm not sure it pinged you

**Comment by romainl** [comment]
I'm sorry it took so long but `CurSearch` now links to `IncSearch` on master.
