### ISSUE TITLE
vim-airline active pane is orange and non-active tab is orange causing confusion

### ISSUE THREAD

**Issue by jimmay5469** [romainl/Apprentice#7]
This has caused a little difficulty for me, I don't know if it is something you have control over because I have not written any themes before myself.  It may be entirely a vim-airline thing for all I know.

Non-active tabs are orange but they draw my eye so I always think they're the active one, especially when I have exactly 2 tabs open (the second tab here is actually the active one):
![screen shot 2015-06-04 at 5 22 18 pm](https://cloud.githubusercontent.com/assets/781752/7994797/4c8f78cc-0ade-11e5-9f9c-24de898f2015.png)

Active pane is orange:
![screen shot 2015-06-04 at 5 05 33 pm](https://cloud.githubusercontent.com/assets/781752/7994517/04183f72-0adc-11e5-9e86-bbde59d3604b.png)

**Comment by romainl** [comment]
Hi. You are right, it is the responsibility of the colorscheme to define that kind of thing and using a bright color for inactive items is definitely a no-no in UX design.

That said, I don't use Airline myself and the Airline colorscheme was contributed by an Apprentice user without me spending much time testing it. As is, it should be considered "alpha" at best and I don't really recommend using it "for real".

Hi will take a look at it anyway. Thank you for this report.

**Comment by jimmay5469** [comment]
If you haven't already taken a look then I would be willing to give it a shot for you, I think I have found the area that would need the edits and it will probably be easier for me to mess with then to have you have to install vim-airline (to be honest I'm not even sure why I'm using it myself, haha).  I'll screenshot my proposed fix so we can easily go back and forth on colors too.

Thanks for the quick response and the awesome Apprentice theme.  It's definitely my favorite that I have seen in a long time!

**Comment by romainl** [comment]
Thank you for your help.

I should have reviewed that airline PR a little more carefully before merging. From your screenshots, I don't think the orange pseudo-tabs fit apprentice at all, they are way too "in your face". It would make a lot more sense to reuse the colors of the native tabline.

Expect an "official" commit soon.

**Comment by djmoch** [comment]
I've also been dissatisfied with the Airline theme. For what it's worth, I always imagined it would look like the Airline builtin Jellybeans theme, but with colors matching Apprentice. Something dark.

If I get a chance to actually pull something together, I'll submit a pull request. Just throwing the suggestion out there in the meantime.

**Comment by djmoch** [comment]
Recommend closing this as a result of merge #22. Active tab is color `#87875F` and non-active tabs are gray.

**Comment by romainl** [comment]
Agreed.
