### ISSUE TITLE
Vim patch 9.0.0032: Cursorline + QuickFixLine no longer look right together

### ISSUE THREAD

**Issue by puremourning** [romainl/Apprentice#72]
There's always been a weird interaction between cursor line highlight and QuickFix current line highlight.

Steps to repro:

* Using vim 9.0.0032 in the vim build directory, run : `env VIMRUNTIME=$(pwd)/runtime ./src/vim --clean --cmd 'set rtp+=$HOME/.vim/bundle/Apprentice' --cmd 'colorscheme apprentice' --cmd 'set termguicolors' --cmd 'set cursorline' -c 'grep edit src/edit.c' -c 'copen'`
* `ctrl-w j` - jump to quick fix
* see that the cursor line highlight and the quick fix line highlights make the text unreadable.

Screenshot:

<img width="679" alt="Screenshot 2022-07-12 at 15 58 55" src="https://user-images.githubusercontent.com/10584846/178521115-9acf8e91-2c6f-4077-892d-6e3bf670e958.png">

Demo showing both current and previous:

https://asciinema.org/a/xxn6mnepdN5qfrYN6GUD8ju9J

**Comment by habamax** [comment]
damn, I thought I was doing it in vim repo :(

**Comment by romainl** [comment]
The issue has been fixed upstream:

<img width="765" alt="Capture d’écran 2022-08-26 à 08 08 52" src="https://user-images.githubusercontent.com/344335/186835107-ebf9e3a3-c8b6-4205-93fb-1b8dd7358304.png">
